### ISSUE TITLE
Resource Storage

### ISSUE THREAD

**Issue by Engineer1119** [spacedecentral/Coral#14]
Define whether the mined material will be stored prior to being processed. If so, identify the requirements for such storage.

**Comment by johnpat007** [comment]
Since the goal is 3D printing using locally available loose surface regolith as feedstock, I don't believe storage will be necessary. A possible concept of operations is for a scoop on an arm attached to the lander to retrieve loose regolith and place in a feed hopper to the printerhead as needed.  JP 8.21.18
