### ISSUE TITLE
Literature review on key Coral topics - Erik Kulu

### ISSUE THREAD

**Issue by erikkulu** [spacedecentral/Coral#47]
In response to #36 to open a new subtask and add your name to the title.

**Comment by timallard** [comment]
Is my query on dust #45 suitable as a subtopic under #36 also?

**Comment by timallard** [comment]
Most info on sediment contents & ore locations given, this was to visualize that first and mining covered, skimming the surface as an excavation method has value, comments on processing most agree having H2O would be mucn easier for that, so, harvesting dirt for pavers and bricks is feasible with it, otherwise sorting fines is by contrast too inefficient overall long-term a constraint.

**Comment by Suzibianco** [comment]
Hi @erikkulu, how is this task going? Do you need any guidance for this? Have you found any relevant information?

**Comment by Suzibianco** [comment]
[Closing this issue as we migrate to a new phase in Coral and new process of how we document issues.]
